# Generated by Django 3.1.2 on 2021-01-26 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nama',
            new_name='name',
        ),
    ]
